/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/css/chat': RouteRecordInfo<'/css/chat', '/css/chat', Record<never, never>, Record<never, never>>,
    '/css/flex': RouteRecordInfo<'/css/flex', '/css/flex', Record<never, never>, Record<never, never>>,
    '/css/resp': RouteRecordInfo<'/css/resp', '/css/resp', Record<never, never>, Record<never, never>>,
    '/ts/array/index01': RouteRecordInfo<'/ts/array/index01', '/ts/array/index01', Record<never, never>, Record<never, never>>,
    '/ts/index01': RouteRecordInfo<'/ts/index01', '/ts/index01', Record<never, never>, Record<never, never>>,
    '/ts/index02': RouteRecordInfo<'/ts/index02', '/ts/index02', Record<never, never>, Record<never, never>>,
    '/ts/index03': RouteRecordInfo<'/ts/index03', '/ts/index03', Record<never, never>, Record<never, never>>,
    '/ts/string/index01': RouteRecordInfo<'/ts/string/index01', '/ts/string/index01', Record<never, never>, Record<never, never>>,
    '/tsx/index01': RouteRecordInfo<'/tsx/index01', '/tsx/index01', Record<never, never>, Record<never, never>>,
    '/vue/01': RouteRecordInfo<'/vue/01', '/vue/01', Record<never, never>, Record<never, never>>,
    '/vue/02': RouteRecordInfo<'/vue/02', '/vue/02', Record<never, never>, Record<never, never>>,
  }
}
