// ============================================================
// 07 内置工具类型：TS 自带，日常开发最常用
// 07 Built-in utility types: shipped with TS, most commonly used day to day
// ============================================================

interface User {
  id: number
  name: string
  age: number
  email?: string
}

// ---------- 对象属性相关 ----------
// ---------- Object property related ----------

// 1. Partial<T>：所有属性变可选
// 1. Partial<T>: make all properties optional
export type PartialUser = Partial<User>

// 2. Required<T>：所有属性变必选
// 2. Required<T>: make all properties required
export type RequiredUser = Required<User>

// 3. Readonly<T>：所有属性变只读（浅层）
// 3. Readonly<T>: make all properties readonly (shallow)
export type ReadonlyUser = Readonly<User>

// 4. Pick<T, K>：挑选部分属性
// 4. Pick<T, K>: pick a subset of properties
export type UserBasic = Pick<User, 'id' | 'name'>

// 5. Omit<T, K>：排除部分属性
// 5. Omit<T, K>: omit a subset of properties
export type UserWithoutAge = Omit<User, 'age'>

// 6. Record<K, V>：构造 key 为 K、值为 V 的对象类型
// 6. Record<K, V>: build an object type with keys K and values V
export type RoleMap = Record<'admin' | 'user', string[]>
export type IdMap = Record<number, User>

// ---------- 联合类型相关 ----------
// ---------- Union type related ----------
type Status = 'pending' | 'done' | 'error' | null | undefined

// 7. Exclude<U, E>：从联合类型中排除
// 7. Exclude<U, E>: exclude members from a union
export type NotError = Exclude<Status, 'error'>

// 8. Extract<U, E>：从联合类型中提取
// 8. Extract<U, E>: extract members from a union
export type OnlyStr = Extract<Status, string>

// 9. NonNullable<T>：排除 null 和 undefined
// 9. NonNullable<T>: exclude null and undefined
export type DefinedStatus = NonNullable<Status>

// ---------- 函数相关 ----------
// ---------- Function related ----------
function createUser(name: string, age: number): User {
  return { id: 1, name, age }
}

// 10. Parameters<F> / ReturnType<F>
export type CreateUserParams = Parameters<typeof createUser> // [name: string, age: number]
export type CreateUserReturn = ReturnType<typeof createUser> // User

// 11. ConstructorParameters<C> / InstanceType<C>
class Foo {
  constructor(public a: string, public b: number) {}
}
export type FooParams = ConstructorParameters<typeof Foo> // [a: string, b: number]
export type FooInstance = InstanceType<typeof Foo> // Foo

// 12. Awaited<T>：取出 Promise 的最终结果类型
// 12. Awaited<T>: get the final resolved type of a Promise
export type A1 = Awaited<Promise<string>> // string
export type A2 = Awaited<Promise<Promise<number>>> // number
export type UserResult = Awaited<ReturnType<typeof fetchUser>>
async function fetchUser(): Promise<User> {
  return { id: 1, name: 'foo', age: 18 }
}

// ---------- 字符串相关 ----------
// ---------- String related ----------

// 13. Uppercase / Lowercase / Capitalize / Uncapitalize
export type Upper = Uppercase<'abc'> // 'ABC'
export type Cap = Capitalize<'abc'> // 'Abc'

// ---------- 组合使用（常见业务场景） ----------
// ---------- Combined usage (common business scenarios) ----------

// 14. 创建表单：id 由后端生成，其余字段必填
// 14. Create form: id is generated by the backend, all other fields required
export type CreateUserForm = Omit<User, 'id'>

// 15. 更新表单：id 必填，其余可选
// 15. Update form: id required, the rest optional
export type UpdateUserForm = Pick<User, 'id'> & Partial<Omit<User, 'id'>>

// 16. 让指定的几个属性变成可选
// 16. Make the specified properties optional
export type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>
export type UserOptionalAge = PartialBy<User, 'age'>

// 17. 取数组元素类型
// 17. Get the array element type
export type Arr = string[]
export type Item = Arr[number] // string

// 18. 让交叉类型展开成一个对象，便于悬浮提示查看
// 18. Flatten an intersection type into a single object for easier hover inspection
export type Simplify<T> = { [K in keyof T]: T[K] } & {}
export type Flat = Simplify<UpdateUserForm>

// 其他：NoInfer<T>（TS 5.4）、ThisParameterType、OmitThisParameter、ThisType 等较少使用，用到时查文档
// Others: NoInfer<T> (TS 5.4), ThisParameterType, OmitThisParameter, ThisType, etc. are rarely used; check the docs when needed
