/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.tsx')['default']
    Card02: typeof import('./components/Card02.vue')['default']
    InputCard: typeof import('./components/InputCard.vue')['default']
    LevelCard: typeof import('./components/LevelCard.vue')['default']
    MyCard: typeof import('./components/MyCard.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeLevelSelector: typeof import('./components/ThreeLevelSelector.vue')['default']
  }
}
