/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card02: typeof import('./components/Card02.vue')['default']
    InputCard: typeof import('./components/InputCard.vue')['default']
    LevelCard: typeof import('./components/LevelCard.vue')['default']
    MyCard: typeof import('./components/MyCard.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeLevelSelector: typeof import('./components/ThreeLevelSelector.vue')['default']
  }
}

// For TSX support
declare global {
  const Card02: typeof import('./components/Card02.vue')['default']
  const InputCard: typeof import('./components/InputCard.vue')['default']
  const LevelCard: typeof import('./components/LevelCard.vue')['default']
  const MyCard: typeof import('./components/MyCard.tsx')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ThreeLevelSelector: typeof import('./components/ThreeLevelSelector.vue')['default']
}